# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: kramdown
author_profile: true
title: "Alexander Zherebtsov"
# logo: "/images/avatar.jpg"
author:
  name             : "Alexander Zherebtsov"
  avatar           : "/images/avatar.jpg"
  bio: "Software/Game Developer"
  links:
    - label: "Email"
      icon: "fas fa-envelope-square"
      url: "mailto:zherebtsovalexander@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/alexander-zherebtsov-17b952aa/"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/aZherebtsov"
    - label: "Itch.io"
      icon: "fab fa-itch-io"
      url: "https://alexlemming.itch.io"
    - label: "GitHub"
      icon: "fab fa-github-square"
      url: "https://github.com/AlexLemminG"
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/Alex_lemminG"
      
atom_feed:
  hide: true

include:
  - _pages
  
plugins:
  - jekyll-include-cache